### ISSUE TITLE
Whether there is a usage instruction for this repo?

### ISSUE THREAD

**Issue by tiandankanfeng** [the-web-history/css-timeline#5]

**Comment by rajasegar** [comment]
What exactly you are looking for?
If you want to run it in local dev environment, just clone it  and 
```
npm install
npm run dev
```
If you want to update or add data about the timeline line events, the instructions are in the readme

**Comment by tiandankanfeng** [comment]
Does this currently run on github pages?

**Comment by tiandankanfeng** [comment]
The repo is excellent, if I want to run it on github pages, is there a detail usage instruction for it?

**Comment by rajasegar** [comment]
Currently it is running on Vercel, if you want to run it on github pages, you should build it for production with
```
npm run build
```
And then follow the instructions here
https://docs.github.com/en/enterprise-server@3.6/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by tiandankanfeng** [comment]
I get it, thanks!
